### ISSUE TITLE
Validator: Extend validator to validate the schema of the default settings file

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/pydotfiles#57]
## Background
- Currently, we don't do any validation of the file that gets referenced in `os.default_settings_file`

## Tasks
- [x] Inside the `/resources/schema` directory, create an `alpha` directory, and move `/resources/schema/alpha.json` -> `/resources/schema/alpha/core.json`
- [x] Inside the validator, we should make it so that it loads in the new correct schema for the core validator
- [x] Create a new validate method that gets called if the `default_settings_file` is not `None`
