### ISSUE TITLE
Get rid of settings file entrypoint assumption in core

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/pydotfiles#67]
## Background
- #65 introduced developer environments, the use of a common schema shared between other schemas, and most importantly a change in the validator to validate all .json/.yaml/.yml files by default.
- What this means is that we are no longer tied to `settings.yaml/json/yml` as the entrypoint for a module. This 

## Tasks
- [ ] Validator: Get rid of default_settings_file in alpha.core schema
- [ ] Core: Get rid of the logic isolating for `settings.yaml/json/yml`, and replace with a tree walk
- [ ] Validator -> Core: Migrate the logic where the files are chosen from the validator to `pydotfiles.common` or someplace else, and then have both core and the validator call this
